name: cover_page
description: A new Flutter project.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Utility Packages
  url_launcher: ^6.3.0
  intl: ^0.19.0
  fluttertoast: ^8.2.8
  dropdown_button2: ^2.3.9
  share_plus: ^9.0.0

  # Animations
  circular_menu: ^4.0.0
  loading_animation_widget: ^1.2.1
  lottie: ^3.1.2
  page_transition: ^2.1.0
  animated_splash_screen: ^1.3.0

  # PDF Packages
  pdf: ^3.11.0
  printing: ^5.13.1
  open_file: ^3.3.2
  path_provider: ^2.1.3

  # Icons
  iconsax: ^0.0.8
  font_awesome_flutter: ^10.7.0
  cupertino_icons: ^1.0.8

  # State Management & Storage
  get: ^4.6.6
  get_storage: ^2.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0 # Use ^4.0.0 only if you're not getting Dart analysis warnings

flutter:
  uses-material-design: true

  assets:
    - assets/images/university_logo/
    - assets/logos/
    - assets/fonts/
    - assets/animations/

  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/open-sans.regular.ttf

    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-Italic.ttf
        - asset: assets/fonts/Poppins-MediumItalic.ttf
          weight: 500
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 800
